import type { Metadata } from "next";
import "../globals.css";
export const metadata: Metadata = {
  title: "Know Ledge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={"flex flex-col items-center justify-center h-screen"}>
      {children}
    </div>
  );
}
